#!/usr/bin/env bash
# This script installs nginx and sets up the required configuration

# Update the package lists for upgrades and new package installations
apt-get update -y

# Install nginx
apt-get install -y nginx

# Start nginx
service nginx start

ufw allow 'Nginx HTTP'

# Create a custom homepage
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart nginx
service nginx restart
