#!/usr/bin/env bash
# This script configures a new Ubuntu machine

# Update and upgrade the system
sudo apt-get update -y
sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Start Nginx
sudo service nginx start

# Create a redirection configuration
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirection

# Enable the configuration
sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
