#!/usr/bin/env bash
# This script configures a new Ubuntu machine

# Update and upgrade the system
sudo apt-get update -y
sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Start Nginx
sudo service nginx start

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Create a new Nginx configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
