#!/usr/bin/env bash
# Configures a new Ubuntu machine with a custom Nginx HTTP response header

# Update and upgrade the system
sudo apt-get update -y
sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx service
sudo service nginx start

# Add the custom header to the Nginx configuration
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        try_files $uri $uri/ =404;
    }
}' | sudo tee /etc/nginx/sites-available/default

# Restart Nginx service to apply the changes
sudo service nginx restart
