#!/usr/bin/env bash
# This script installs and configures HAproxy on a new Ubuntu machine

# Update and upgrade the system
sudo apt-get update -y
sudo apt-get upgrade -y

# Install HAproxy
sudo apt-get install -y haproxy

# Configure HAproxy
echo '
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server web01 [STUDENT_ID]-web-01:80 check
   server web02 [STUDENT_ID]-web-02:80 check
' | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAproxy service to apply the changes
sudo service haproxy restart
